# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
# If you see this message and want to make changes, please edit the template at:
# https://github.com/seniorGolang/tg

class Tg < Formula
  desc "Tool Gateway - расширяемая платформа для выполнения задач через плагины"
  homepage "https://github.com/seniorGolang/tg"
  license "MIT"
  version "3.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.7/tg_3.0.7_darwin_arm64.tar.gz"
      sha256 "c616aef2d357d68a93c011d77a8643d8562c3d559346fb59e6d64fc4bb562940"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.7/tg_3.0.7_darwin_amd64.tar.gz"
      sha256 "0aef4d668f0ebbe911e967eaf8cbc293320d75e2197236db85cfc9e0c1f37b0e"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.7/tg_3.0.7_linux_arm64.tar.gz"
      sha256 "c0187de93ac76e80d7bea510e55aa56522cbb29644748915f8877a3b29b07ccd"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.7/tg_3.0.7_linux_amd64.tar.gz"
      sha256 "dd276f6ce77bf5068e9a57a917656388cf8ebb2e1e23c88d8cb42e3ed01eba35"
    end
  end

  def install
    bin.install "tg"
  end

  test do
    system "#{bin}/tg", "--help"
  end
end
