# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
# If you see this message and want to make changes, please edit the template at:
# https://github.com/seniorGolang/tg

class Tg < Formula
  desc "Tool Gateway - расширяемая платформа для выполнения задач через плагины"
  homepage "https://github.com/seniorGolang/tg"
  license "MIT"
  version "3.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.5/tg_3.0.5_darwin_arm64.tar.gz"
      sha256 "a70d679aeddb3a305a48460d07c288e829fe81a7e6d41b97155d4a55701ef6b0"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.5/tg_3.0.5_darwin_amd64.tar.gz"
      sha256 "f507b288089f53959dc3a2ea519e3ba2a683786f08f5fddcb812f490e2895083"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.5/tg_3.0.5_linux_arm64.tar.gz"
      sha256 "c1290044dd6688aecde6238655a897b9f5109d469c3bcc78bc4c6d95d356faa2"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.5/tg_3.0.5_linux_amd64.tar.gz"
      sha256 "c79fb57642741b467a4917b0425e4726d8afea6b69cbb9ed49140c6f0c5d2627"
    end
  end

  def install
    bin.install "tg"
  end

  test do
    system "#{bin}/tg", "--help"
  end
end
