# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
# If you see this message and want to make changes, please edit the template at:
# https://github.com/seniorGolang/tg

class Tg < Formula
  desc "Tool Gateway - расширяемая платформа для выполнения задач через плагины"
  homepage "https://github.com/seniorGolang/tg"
  license "MIT"
  version "3.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.2/tg_3.0.2_darwin_arm64.tar.gz"
      sha256 "47b9f64119cda9ac92696282c099c7d5f70cea0a5507f5652885920941acbd31"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.2/tg_3.0.2_darwin_amd64.tar.gz"
      sha256 "f02f2070e8eb8e23fb9296007dc383f6880834b607a9a38a32b016ee0c9a1f7f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.2/tg_3.0.2_linux_arm64.tar.gz"
      sha256 "043eed633b9e7bf1a8774a1ef8fd1238575128a16c7cc9cbb619a25b8aff8fc0"
    else
      url "https://github.com/seniorGolang/tg/releases/download/v3.0.2/tg_3.0.2_linux_amd64.tar.gz"
      sha256 "1a4b60c560377f956e723d484171241c8b706e02d00681b9552106ee916015bb"
    end
  end

  def install
    bin.install "tg"
  end

  test do
    system "#{bin}/tg", "--help"
  end
end
